export interface AIItem {
  id: string;
  symbol: string;
  name: string;
  category: string;
  logo: string;
  borderColor: string;
  glowColor: string;
  description: string;
  col: number;
  row: number;
}

export const AIS: AIItem[] = [
  // Fila 1 - Extremos
  {
    id: "chatgpt",
    symbol: "GPT",
    name: "ChatGPT",
    category: "LLM",
    logo: "https://upload.wikimedia.org/wikipedia/commons/0/04/ChatGPT_logo.svg",
    borderColor: "border-emerald-500",
    glowColor: "hover:shadow-emerald-500/40",
    description: "Asistente conversacional multimodal de OpenAI.",
    col: 1,
    row: 1,
  },
  {
    id: "claude",
    symbol: "Cl",
    name: "Claude",
    category: "NLP",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Anthropic_logo.svg/200px-Anthropic_logo.svg.png",
    borderColor: "border-orange-400",
    glowColor: "hover:shadow-orange-400/40",
    description: "Modelo de Anthropic enfocado en razonamiento.",
    col: 10,
    row: 1,
  },

  // Fila 2 - Primer bloque LLMs/Texto
  {
    id: "gemini",
    symbol: "Gm",
    name: "Gemini",
    category: "LLM",
    logo: "https://ui-avatars.com/api/?name=Gemini&background=2563eb&color=fff",
    borderColor: "border-blue-500",
    glowColor: "hover:shadow-blue-500/40",
    description: "Modelo multimodal avanzado de Google.",
    col: 1,
    row: 2,
  },
  {
    id: "mistral",
    symbol: "Ms",
    name: "Mistral",
    category: "LLM",
    logo: "https://ui-avatars.com/api/?name=Mistral&background=f97316&color=fff",
    borderColor: "border-orange-500",
    glowColor: "hover:shadow-orange-500/40",
    description: "Start-up europea de modelos eficientes.",
    col: 2,
    row: 2,
  },
  {
    id: "cohere",
    symbol: "Co",
    name: "Cohere",
    category: "NLP",
    logo: "https://ui-avatars.com/api/?name=Cohere&background=16a34a&color=fff",
    borderColor: "border-green-600",
    glowColor: "hover:shadow-green-600/40",
    description: "IA centrada en búsqueda empresarial.",
    col: 8,
    row: 2,
  },
  {
    id: "characterai",
    symbol: "Ca",
    name: "Character",
    category: "Chat",
    logo: "https://ui-avatars.com/api/?name=Char&background=8b5cf6&color=fff",
    borderColor: "border-violet-500",
    glowColor: "hover:shadow-violet-500/40",
    description: "Plataforma de avatares conversacionales.",
    col: 9,
    row: 2,
  },
  {
    id: "poe",
    symbol: "Po",
    name: "Poe",
    category: "Chat",
    logo: "https://ui-avatars.com/api/?name=Poe&background=9333ea&color=fff",
    borderColor: "border-purple-600",
    glowColor: "hover:shadow-purple-600/40",
    description: "Portal rápido a múltiples chatbots.",
    col: 10,
    row: 2,
  },

  // Fila 3 - Medio bloque Productividad/Texto
  {
    id: "perplexity",
    symbol: "Px",
    name: "Perplexity",
    category: "Search",
    logo: "https://ui-avatars.com/api/?name=Perplexity&background=22d3ee&color=000",
    borderColor: "border-cyan-400",
    glowColor: "hover:shadow-cyan-400/40",
    description: "Motor de búsqueda IA con respuestas directas.",
    col: 1,
    row: 3,
  },
  {
    id: "jasper",
    symbol: "Js",
    name: "Jasper",
    category: "Writing",
    logo: "https://ui-avatars.com/api/?name=Jasper&background=ec4899&color=fff",
    borderColor: "border-pink-500",
    glowColor: "hover:shadow-pink-500/40",
    description: "Especializada en marketing y blogs.",
    col: 2,
    row: 3,
  },
  {
    id: "copyai",
    symbol: "Cy",
    name: "Copy.ai",
    category: "Writing",
    logo: "https://ui-avatars.com/api/?name=Copy&background=34d399&color=000",
    borderColor: "border-emerald-400",
    glowColor: "hover:shadow-emerald-400/40",
    description: "Redacta textos comerciales ágiles.",
    col: 8,
    row: 3,
  },
  {
    id: "notionai",
    symbol: "Nt",
    name: "Notion AI",
    category: "Product",
    logo: "https://ui-avatars.com/api/?name=Notion&background=d1d5db&color=000",
    borderColor: "border-gray-300",
    glowColor: "hover:shadow-gray-300/40",
    description: "Asistente inmerso en tu entorno de Notion.",
    col: 9,
    row: 3,
  },
  {
    id: "pi",
    symbol: "Pi",
    name: "Pi",
    category: "Chat",
    logo: "https://ui-avatars.com/api/?name=Pi&background=6ee7b7&color=000",
    borderColor: "border-emerald-300",
    glowColor: "hover:shadow-emerald-300/40",
    description: "Compañera conversacional amigable.",
    col: 10,
    row: 3,
  },

  // Fila 4 - Código (Metales de Transición)
  {
    id: "copilot",
    symbol: "Cp",
    name: "Copilot",
    category: "Code",
    logo: "https://ui-avatars.com/api/?name=Copilot&background=374151&color=fff",
    borderColor: "border-gray-400",
    glowColor: "hover:shadow-gray-400/40",
    description: "Asistente integrado en tu editor.",
    col: 1,
    row: 4,
  },
  {
    id: "cursor",
    symbol: "Cr",
    name: "Cursor",
    category: "Code",
    logo: "https://ui-avatars.com/api/?name=Cursor&background=60a5fa&color=fff",
    borderColor: "border-blue-400",
    glowColor: "hover:shadow-blue-400/40",
    description: "Editor avanzado con IA de vanguardia.",
    col: 2,
    row: 4,
  },
  {
    id: "devin",
    symbol: "Dv",
    name: "Devin",
    category: "Code",
    logo: "https://ui-avatars.com/api/?name=Devin&background=818cf8&color=fff",
    borderColor: "border-indigo-400",
    glowColor: "hover:shadow-indigo-400/40",
    description: "Primer ingeniero de software IA autónomo.",
    col: 3,
    row: 4,
  },
  {
    id: "v0",
    symbol: "v0",
    name: "v0",
    category: "Code",
    logo: "https://ui-avatars.com/api/?name=v0&background=18181b&color=fff",
    borderColor: "border-zinc-800",
    glowColor: "hover:shadow-zinc-800/40",
    description: "Generador de UI en React por Vercel.",
    col: 4,
    row: 4,
  },
  {
    id: "alphacode",
    symbol: "Ac",
    name: "AlphaCode",
    category: "Code",
    logo: "https://ui-avatars.com/api/?name=Alpha&background=2563eb&color=fff",
    borderColor: "border-blue-600",
    glowColor: "hover:shadow-blue-600/40",
    description: "Resuelve problemas de programación a escala.",
    col: 5,
    row: 4,
  },
  // Híbridos Open Source / Plataforma
  {
    id: "huggingface",
    symbol: "Hf",
    name: "HggFace",
    category: "Platform",
    logo: "https://ui-avatars.com/api/?name=HF&background=eab308&color=000",
    borderColor: "border-yellow-500",
    glowColor: "hover:shadow-yellow-500/40",
    description: "Ecosistema principal de modelos ML.",
    col: 6,
    row: 4,
  },
  {
    id: "groq",
    symbol: "Gq",
    name: "Groq",
    category: "Ll/HW",
    logo: "https://ui-avatars.com/api/?name=Groq&background=ea580c&color=fff",
    borderColor: "border-orange-600",
    glowColor: "hover:shadow-orange-600/40",
    description: "Procesadores especiales ultrarrapidos.",
    col: 7,
    row: 4,
  },
  {
    id: "llama3",
    symbol: "Lm",
    name: "Llama 3",
    category: "Op Src",
    logo: "https://ui-avatars.com/api/?name=Llama&background=2563eb&color=fff",
    borderColor: "border-blue-600",
    glowColor: "hover:shadow-blue-600/40",
    description: "Potente modelo de código abierto de Meta.",
    col: 8,
    row: 4,
  },
  {
    id: "ollama",
    symbol: "Ol",
    name: "Ollama",
    category: "Op Src",
    logo: "https://ui-avatars.com/api/?name=Ollama&background=d4d4d8&color=000",
    borderColor: "border-zinc-300",
    glowColor: "hover:shadow-zinc-300/40",
    description: "Ejecuta LLMs fácilmente localmente.",
    col: 9,
    row: 4,
  },
  {
    id: "midjourney",
    symbol: "Mj",
    name: "MdJrny",
    category: "Image",
    logo: "https://ui-avatars.com/api/?name=Midjourney&background=8b5cf6&color=fff",
    borderColor: "border-purple-500",
    glowColor: "hover:shadow-purple-500/40",
    description: "Generador hiperrealista artístico.",
    col: 10,
    row: 4,
  },

  // Fila 5 - Multimedia (Video, Audio, Imagen)
  {
    id: "dalle3",
    symbol: "Dl",
    name: "DALL-E",
    category: "Image",
    logo: "https://ui-avatars.com/api/?name=DALLE&background=facc15&color=000",
    borderColor: "border-yellow-400",
    glowColor: "hover:shadow-yellow-400/40",
    description: "Generador de imágenes preciso por OpenAI.",
    col: 1,
    row: 5,
  },
  {
    id: "stablediffusion",
    symbol: "Sd",
    name: "StblDff",
    category: "Image",
    logo: "https://ui-avatars.com/api/?name=SD&background=6366f1&color=fff",
    borderColor: "border-indigo-500",
    glowColor: "hover:shadow-indigo-500/40",
    description: "Modelo de imagen de código abierto local.",
    col: 2,
    row: 5,
  },
  {
    id: "leonardo",
    symbol: "Le",
    name: "Leonardo",
    category: "Image",
    logo: "https://ui-avatars.com/api/?name=Leonardo&background=14b8a6&color=fff",
    borderColor: "border-teal-500",
    glowColor: "hover:shadow-teal-500/40",
    description: "Creación de arte y diseño de juegos.",
    col: 3,
    row: 5,
  },
  {
    id: "firefly",
    symbol: "Ff",
    name: "Firefly",
    category: "Image",
    logo: "https://ui-avatars.com/api/?name=Firefly&background=dc2626&color=fff",
    borderColor: "border-red-600",
    glowColor: "hover:shadow-red-600/40",
    description: "IA generativa de Adobe con diseño seguro.",
    col: 4,
    row: 5,
  },
  {
    id: "sora",
    symbol: "Sr",
    name: "Sora",
    category: "Video",
    logo: "https://ui-avatars.com/api/?name=Sora&background=ef4444&color=fff",
    borderColor: "border-red-500",
    glowColor: "hover:shadow-red-500/40",
    description: "Generador de video hiperrealista.",
    col: 5,
    row: 5,
  },
  {
    id: "runway",
    symbol: "Rw",
    name: "Runway",
    category: "Video",
    logo: "https://ui-avatars.com/api/?name=Runway&background=d946ef&color=fff",
    borderColor: "border-fuchsia-500",
    glowColor: "hover:shadow-fuchsia-500/40",
    description: "Edición y creación de video profesional.",
    col: 6,
    row: 5,
  },
  {
    id: "synthesia",
    symbol: "Sy",
    name: "Synth",
    category: "Video",
    logo: "https://ui-avatars.com/api/?name=Synthesia&background=60a5fa&color=fff",
    borderColor: "border-blue-400",
    glowColor: "hover:shadow-blue-400/40",
    description: "Avatares de video y presentadores IA.",
    col: 7,
    row: 5,
  },
  {
    id: "elevenlabs",
    symbol: "El",
    name: "11Labs",
    category: "Audio",
    logo: "https://ui-avatars.com/api/?name=Eleven&background=a1a1aa&color=000",
    borderColor: "border-zinc-400",
    glowColor: "hover:shadow-zinc-400/40",
    description: "Voces sintéticas realistas y clonación.",
    col: 8,
    row: 5,
  },
  {
    id: "suno",
    symbol: "Su",
    name: "Suno",
    category: "Audio",
    logo: "https://ui-avatars.com/api/?name=Suno&background=fbbf24&color=000",
    borderColor: "border-amber-400",
    glowColor: "hover:shadow-amber-400/40",
    description: "Composición de canciones y música completas.",
    col: 9,
    row: 5,
  },
  {
    id: "udio",
    symbol: "Ud",
    name: "Udio",
    category: "Audio",
    logo: "https://ui-avatars.com/api/?name=Udio&background=38bdf8&color=000",
    borderColor: "border-sky-400",
    glowColor: "hover:shadow-sky-400/40",
    description: "Creación musical y acústica de alta gama.",
    col: 10,
    row: 5,
  }
];

export function getAIById(id: string) {
  return AIS.find((ai) => ai.id === id);
}